### ISSUE TITLE
Change CWD / Insert path fails quietly if no project is selected

### ISSUE THREAD

**Issue by Naatan** [Naatan/komodo-terminal-butterfly#12]
Does nothing.

**Comment by Defman21** [comment]
It works for me. Anything in your log?

**Comment by Naatan** [comment]
Do'h. I had no Project open. Maybe this should be changed to "of current Places directory" ?

**Comment by Defman21** [comment]
Is there a way to do it except for reading current `pwd`?

**Comment by Naatan** [comment]
I'm not sure what you mean?

**Comment by Defman21** [comment]
Nvm, gonna look into this. Please update your issue title :)

**Comment by Defman21** [comment]
And yeah Nathan, if you don't have any project opened it should show you an error about it.

**Comment by Naatan** [comment]
If you base it on Places then it would be a non-issue. And is probably a more desirable behaviour anyway.

**Comment by Naatan** [comment]
If you intend to keep using the project path I would suggest you make the menu items disabled if no project is open.

**Comment by Defman21** [comment]
Gonna go with current Places of directory.
