### ISSUE TITLE
Change CWD / Insert Path makes scrollTop jump for Buffer

### ISSUE THREAD

**Issue by Naatan** [Naatan/komodo-terminal-butterfly#13]
When changing CWD to current buffer or inserting the path of the current buffer the terminal scrolls all the way to the bottom and the input is not visible anymore, you have to manually scroll up to continue typing.

**Comment by Defman21** [comment]
Not something I'm able to reproduce. If you change line #137 in file `content/widget.js` to `insertIntoButterfly(`cd ${string}`);`, are you still able to reproduce it?

**Comment by Naatan** [comment]
Yes, that seems to work.

I don't think calling clear after changing the CWD is desirable anyway. That's up to the user.

**Comment by Defman21** [comment]
Ok, will remove it.
