### ISSUE TITLE
Remove "leave page" warning when closing Komodo

### ISSUE THREAD

**Issue by Defman21** [Naatan/komodo-terminal-butterfly#4]

**Comment by Defman21** [comment]
Seems like it's not that easy as I thought and it requires some upstream fixes. At least I'm not able to prevent this by setting browser.contentWindow.onbeforeunload to null.

**Comment by Defman21** [comment]
I'm not sure how good the fix is, so if an JS expert say something about it - I'd be very happy (@Naatan?)

**Comment by Naatan** [comment]
Looks sane to me.

**Comment by Defman21** [comment]
Good!
