### ISSUE TITLE
Add a way of quickly navigating to the current buffer path or current project path

### ISSUE THREAD

**Issue by Naatan** [Naatan/komodo-terminal-butterfly#6]
eg. right click tab, show:
- Change CWD to path of current buffer
- Change CWD to path of current project 
- ---
- Insert path of current buffer
- Insert path of current project

**Comment by Defman21** [comment]
Interesting idea!

**Comment by Defman21** [comment]
Buffer refers to current file?

**Comment by Naatan** [comment]
Yes

**Comment by Defman21** [comment]
it works perfectly in bash but with some "animations" in zsh. Don't want to dig in it nor I don't see any way to fix it, seems like it's a bug in butterfly.

**Comment by Defman21** [comment]
I think I should use dtd files for these labels, but does it matter?

/cc @Naatan
