### ISSUE TITLE
Remove caret blinking animation

### ISSUE THREAD

**Issue by Naatan** [Naatan/komodo-terminal-butterfly#7]
it's inconsistent with the UX of Komodo (ie. it should not fade in and out).

**Comment by Defman21** [comment]
It's on the way!

**Comment by Naatan** [comment]
Wouldn't that remove the blinking altogether? My suggestion was to remove the fading animation, the blinking should still occur.

**Comment by Defman21** [comment]
It's done with butterfly's js, so I'm not sure this is possible.

**Comment by Defman21** [comment]
hmm, gonna try to remove transition!

**Comment by Naatan** [comment]
You can override any part of butterfly css. Pretty sure this is just a css animation.

**Comment by Defman21** [comment]
@Naatan it keeps adding and removing `.reverse-video` to the cursor, so I guess it's done with js. I'm gonna dig in it though.

**Comment by Naatan** [comment]
.reverse-video likely has an animation set on it.

Try:

```
.reverse-video {
  animation: none !important;
  transition: none !important;
}
```

**Comment by Defman21** [comment]
Doesn't work :(
I'm still searching.

**Comment by Defman21** [comment]
Aha, that did the trick!
